N = input('Digite algo:')
print(N.isalnum())
print(N.isalpha())
print(N.isdigit())
print(N.isprintable())
print(N.isupper())
print(N.isidentifier())
print(N.istitle())
print(N.isnumeric())
print(N.islower())